name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: cinemaHub
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore
        run: dotnet restore ./AuthenticationAndAuthorization.sln
        
      - name: Build
        run: dotnet build ./AuthenticationAndAuthorization.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./AuthenticationAndAuthorization.sln --configuration Release --no-build 
